Bugfixing copy of hudson.model.AbstractItem.
Reason:
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 0
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
        at java.base/java.lang.String.substring(String.java:2709)
        at java.base/java.lang.String.substring(String.java:2682)
        at hudson.model.AbstractItem.getUrl(AbstractItem.java:549)
        at org.jenkins.ci.plugins.keyboard_shortcuts.JobUtils.toJSONObject(JobUtils.java:110)
        at org.jenkins.ci.plugins.keyboard_shortcuts.JobUtils.getJobsAsJsonArray(JobUtils.java:60)
        at org.jenkins.ci.plugins.keyboard_shortcuts.JobUtils.getAllJobsAsJsonArray(JobUtils.java:52)
        at org.jenkins.ci.plugins.keyboard_shortcuts.KeyboardShortcutsPageDecorator.getAllJobsAsJson(KeyboardShortcutsPageDecorator.java:60)
Caused: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor273.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
        at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)
        at org.apache.commons.jexl.parser.ASTArrayAccess.evaluateExpr(ASTArrayAccess.java:185)
        at org.apache.commons.jexl.parser.ASTIdentifier.execute(ASTIdentifier.java:75)
        at org.apache.commons.jexl.parser.ASTReference.execute(ASTReference.java:83)
        at org.apache.commons.jexl.parser.ASTReference.value(ASTReference.java:57)